name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform Action'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # Backend ke liye zaroori hai agar tumne storage account use kiya hai
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }} 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve

    # Sabse important: Credentials Apply ke BAAD lo taaki Kubernetes resources deploy ho sakein
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZ_RG }} --name voting-app-aks --overwrite-existing